### ISSUE TITLE
one question on input

### ISSUE THREAD

**Issue by Yangxiaojun1230** [monocongo/tfod_ssd#13]
how did you preprocess your training data，since the picture is not 300x300，maybe 900x300 .  if directly input ，the rate of object will be changed，how to solve such problem，thx

**Comment by monocongo** [comment]
My training/validation images dataset (in TFRecords) has resolution 1024x768. My understanding is that the model training script provided by the TFOD API is handling the resizing of input images when it trains using this input dataset.

**Comment by Yangxiaojun1230** [comment]
> 
> 
> My training/validation images dataset (in TFRecords) has resolution 1024x768. My understanding is that the model training script provided by the TFOD API is handling the resizing of input images when it trains using this input dataset.

I very appreciate it  you reply my question. From my perspective if we keep training data and test data in same scale, it won't be a problem. And i did some test to verify that if used a open source model, the input picture should keep the original scale .
